services:
  - type: web
    name: gestor-contable
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/gestorContable-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
